export const companies: { value: string; label: string }[] = [
    { value: 'time4education', label: 'T.I.M.E. (time4education)' },
    // India Unicorns & Top Tech
    { value: 'paytm', label: 'Paytm' },
    { value: 'byjus', label: "Byju's" },
    { value: 'ola-cabs', label: 'Ola Cabs' },
    { value: 'swiggy', label: 'Swiggy' },
    { value: 'zomato', label: 'Zomato' },
    { value: 'oyo-rooms', label: 'Oyo Rooms' },
    { value: 'dream11', label: 'Dream11' },
    { value: 'razorpay', label: 'Razorpay' },
    { value: 'cred', label: 'CRED' },
    { value: 'udaan', label: 'Udaan' },
    { value: 'policybazaar', label: 'Policybazaar' },
    { value: 'meesho', label: 'Meesho' },
    { value: 'phonepe', label: 'PhonePe' },
    { value: 'upstox', label: 'Upstox' },
    { value: 'zerodha', label: 'Zerodha' },
    { value: 'bharatpe', label: 'BharatPe' },
    { value: 'cars24', label: 'Cars24' },
    { value: 'lenskart', label: 'Lenskart' },
    { value: 'nykaa', label: 'Nykaa' },
    { value: 'unacademy', label: 'Unacademy' },
    { value: 'urban-company', label: 'Urban Company' },
    { value: 'delhivery', label: 'Delhivery' },
    { value: 'freshworks', label: 'Freshworks' },
    { value: 'groww', label: 'Groww' },
    { value: 'inmobi', label: 'InMobi' },
    { value: 'ola-electric', label: 'Ola Electric' },
    { value: 'chargebee', label: 'Chargebee' },
    { value: 'curefit', label: 'Cure.fit' },
    { value: 'digit-insurance', label: 'Digit Insurance' },
    { value: 'firstcry', label: 'FirstCry' },
    { value: 'ofbusiness', label: 'OfBusiness' },
    { value: 'apna', label: 'Apna' },
    // Top Indian Companies
    { value: 'reliance-industries', label: 'Reliance Industries' },
    { value: 'tata-consultancy-services', label: 'Tata Consultancy Services (TCS)' },
    { value: 'infosys', label: 'Infosys' },
    { value: 'wipro', label: 'Wipro' },
    { value: 'hdfc-bank', label: 'HDFC Bank' },
    { value: 'icici-bank', label: 'ICICI Bank' },
    { value: 'state-bank-of-india', label: 'State Bank of India (SBI)' },
    { value: 'axis-bank', label: 'Axis Bank' },
    { value: 'kotak-mahindra-bank', label: 'Kotak Mahindra Bank' },
    { value: 'bharti-airtel', label: 'Bharti Airtel' },
    { value: 'reliance-jio', label: 'Reliance Jio' },
    { value: 'bajaj-finance', label: 'Bajaj Finance' },
    { value: 'hindustan-unilever', label: 'Hindustan Unilever' },
    { value: 'itc-limited', label: 'ITC Limited' },
    { value: 'larsen-toubro', label: 'Larsen & Toubro' },
    { value: 'mahindra-mahindra', label: 'Mahindra & Mahindra' },
    { value: 'maruti-suzuki', label: 'Maruti Suzuki' },
    { value: 'sun-pharma', label: 'Sun Pharma' },
    { value: 'dr-reddys-laboratories', label: "Dr. Reddy's Laboratories" },
    { value: 'asian-paints', label: 'Asian Paints' },
    { value: 'adani-ports', label: 'Adani Ports' },
    { value: 'titan-company', label: 'Titan Company' },
    { value: 'tech-mahindra', label: 'Tech Mahindra' },
    { value: 'hcl-technologies', label: 'HCL Technologies' },
    { value: 'hero-motocorp', label: 'Hero MotoCorp' },
    { value: 'hindalco', label: 'Hindalco' },
    { value: 'jsw-steel', label: 'JSW Steel' },
    { value: 'tata-steel', label: 'Tata Steel' },
    { value: 'tata-motors', label: 'Tata Motors' },
    { value: 'apollo-hospitals', label: 'Apollo Hospitals'},
    { value: 'cipla', label: 'Cipla' },
    { value: 'godrej', label: 'Godrej' },
    { value: 'havells', label: 'Havells' },
    { value: 'indigo', label: 'IndiGo Airlines' },
    { value: 'jet-airways', label: 'Jet Airways' },
    { value: 'mindtree', label: 'Mindtree' },
    { value: 'mrf', label: 'MRF' },
    { value: 'pidilite', label: 'Pidilite' },
    { value: 'ultratech-cement', label: 'UltraTech Cement' },
    // Global Tech Giants
    { value: 'google', label: 'Google' },
    { value: 'alphabet', label: 'Alphabet' },
    { value: 'amazon', label: 'Amazon' },
    { value: 'meta', label: 'Meta' },
    { value: 'facebook', label: 'Facebook' },
    { value: 'apple', label: 'Apple' },
    { value: 'microsoft', label: 'Microsoft' },
    { value: 'netflix', label: 'Netflix' },
    { value: 'tesla', label: 'Tesla' },
    { value: 'oracle', label: 'Oracle' },
    { value: 'sap', label: 'SAP' },
    { value: 'ibm', label: 'IBM' },
    { value: 'cisco', label: 'Cisco' },
    { value: 'intel', label: 'Intel' },
    { value: 'nvidia', label: 'Nvidia' },
    { value: 'amd', label: 'AMD' },
    { value: 'qualcomm', label: 'Qualcomm' },
    { value: 'adobe', label: 'Adobe' },
    { value: 'salesforce', label: 'Salesforce' },
    { value: 'vmware', label: 'VMware' },
    { value: 'dell', label: 'Dell' },
    { value: 'hp', label: 'HP' },
    { value: 'sony', label: 'Sony' },
    { value: 'samsung', label: 'Samsung' },
    { value: 'huawei', label: 'Huawei' },
    { value: 'xiaomi', label: 'Xiaomi' },
    { value: 'tencent', label: 'Tencent' },
    { value: 'alibaba', label: 'Alibaba' },
    { value: 'bytedance', label: 'ByteDance' },
    { value: 'spotify', label: 'Spotify' },
    { value: 'uber', label: 'Uber' },
    { value: 'airbnb', label: 'Airbnb' },
    { value: 'linkedin', label: 'LinkedIn' },
    { value: 'twitter', label: 'Twitter (X)' },
    { value: 'zoom', label: 'Zoom' },
    { value: 'slack', label: 'Slack' },
    { value: 'dropbox', label: 'Dropbox' },
    { value: 'shopify', label: 'Shopify' },
    { value: 'atlassian', label: 'Atlassian' },
    { value: 'intuit', label: 'Intuit' },
    { value: 'paypal', label: 'PayPal' },
    { value: 'square', label: 'Square' },
    { value: 'stripe', label: 'Stripe' },
    // Top Consulting Firms
    { value: 'mckinsey', label: 'McKinsey & Company' },
    { value: 'bcg', label: 'Boston Consulting Group (BCG)' },
    { value: 'bain', label: 'Bain & Company' },
    { value: 'deloitte', label: 'Deloitte' },
    { value: 'pwc', label: 'PwC' },
    { value: 'ey', label: 'EY' },
    { value: 'kpmg', label: 'KPMG' },
    { value: 'accenture', label: 'Accenture' },
    { value: 'capgemini', label: 'Capgemini' },
    { value: 'cognizant', label: 'Cognizant' },
    { value: 'bain-capability-network', label: 'Bain Capability Network' },
    { value: 'aon-hewitt', label: 'Aon Hewitt'},
    // Top Finance/Banking
    { value: 'goldman-sachs', label: 'Goldman Sachs' },
    { value: 'jpmorgan-chase', label: 'JPMorgan Chase & Co.' },
    { value: 'morgan-stanley', label: 'Morgan Stanley' },
    { value: 'bank-of-america', label: 'Bank of America' },
    { value: 'citigroup', label: 'Citigroup' },
    { value: 'wells-fargo', label: 'Wells Fargo' },
    { value: 'hsbc', label: 'HSBC' },
    { value: 'deutsche-bank', label: 'Deutsche Bank' },
    { value: 'barclays', label: 'Barclays' },
    { value: 'american-express', label: 'American Express' },
    { value: 'mastercard', label: 'Mastercard' },
    { value: 'visa', label: 'Visa' },
    { value: 'blackrock', label: 'BlackRock' },
    { value: 'berkshire-hathaway', label: 'Berkshire Hathaway' },
    // FMCG / Retail
    { value: 'walmart', label: 'Walmart' },
    { value: 'flipkart', label: 'Flipkart' },
    { value: 'costco', label: 'Costco' },
    { value: 'procter-gamble', label: 'Procter & Gamble' },
    { value: 'johnson-johnson', label: 'Johnson & Johnson' },
    { value: 'cocacola', label: 'The Coca-Cola Company' },
    { value: 'pepsico', label: 'PepsiCo' },
    { value: 'nestle', label: 'Nestlé' },
    { value: 'unilever', label: 'Unilever' },
    { value: 'mcdonalds', label: "McDonald's" },
    { value: 'starbucks', label: 'Starbucks' },
    { value: 'nike', label: 'Nike' },
    { value: 'adidas', label: 'Adidas' },
    { value: 'ikea', label: 'IKEA' },
    { value: 'loreal', label: "L'Oréal" },
    { value: 'reckitt', label: 'Reckitt' },
    { value: 'dabur', label: 'Dabur' },
    { value: 'patanjali', label: 'Patanjali' },
    { value: 'britannia', label: 'Britannia' },
    // Automotive
    { value: 'ford', label: 'Ford' },
    { value: 'general-motors', label: 'General Motors' },
    { value: 'toyota', label: 'Toyota' },
    { value: 'volkswagen', label: 'Volkswagen' },
    { value: 'bmw', label: 'BMW' },
    { value: 'mercedes-benz', label: 'Mercedes-Benz' },
    { value: 'honda', label: 'Honda' },
    { value: 'hyundai', label: 'Hyundai' },
    { value: 'tvs', label: 'TVS' },
    { value: 'bajaj-auto', label: 'Bajaj Auto' },
    // Healthcare & Pharma
    { value: 'pfizer', label: 'Pfizer' },
    { value: 'merck', label: 'Merck' },
    { value: 'novartis', label: 'Novartis' },
    { value: 'roche', label: 'Roche' },
    { value: 'astrazeneca', label: 'AstraZeneca' },
    { value: 'gsk', label: 'GSK' },
    { value: 'sanofi', label: 'Sanofi' },
    { value: 'biocon', label: 'Biocon' },
    { value: 'lupin', label: 'Lupin' },
    // Conglomerates
    { value: 'general-electric', label: 'General Electric' },
    { value: 'siemens', label: 'Siemens' },
    { value: 'bosch', label: 'Bosch'},
    { value: '3m', label: '3M' },
    { value: 'honeywell', label: 'Honeywell' },
    // Media & Entertainment
    { value: 'disney', label: 'The Walt Disney Company' },
    { value: 'comcast', label: 'Comcast' },
    { value: 'viacom18', label: 'Viacom18' },
    { value: 'zee-entertainment', label: 'Zee Entertainment' },
    { value: 'sony-pictures', label: 'Sony Pictures' },
    // Telecom
    { value: 'verizon', label: 'Verizon' },
    { value: 'att', label: 'AT&T' },
    { value: 'vodafone-idea', label: 'Vodafone Idea' },
    // Energy
    { value: 'exxonmobil', label: 'ExxonMobil' },
    { value: 'shell', label: 'Shell' },
    { value: 'chevron', label: 'Chevron' },
    { value: 'bp', label: 'BP' },
    { value: 'ongc', label: 'ONGC' },
    { value: 'indian-oil', label: 'Indian Oil' },
    // Aviation
    { value: 'boeing', label: 'Boeing' },
    { value: 'airbus', label: 'Airbus' },
    { value: 'air-india', label: 'Air India' },
    { value: 'spicejet', label: 'SpiceJet' },
    { value: 'vistara', label: 'Vistara' },
    // Manufacturing / Other
    { value: 'schaeffler', label: 'Schaeffler'},
    { value: 'arcelormittal', label: 'ArcelorMittal' },
    { value: 'anytime-fitness', label: 'Anytime Fitness'},
    { value: 'apple-fitness-plus', label: 'Apple Fitness+' },
];
