export const jobRoles: { value: string; label: string }[] = [
    // Software & Tech
    { value: 'software-engineer', label: 'Software Engineer' },
    { value: 'frontend-developer', label: 'Frontend Developer' },
    { value: 'backend-developer', label: 'Backend Developer' },
    { value: 'full-stack-developer', label: 'Full Stack Developer' },
    { value: 'mobile-app-developer', label: 'Mobile App Developer' },
    { value: 'devops-engineer', label: 'DevOps Engineer' },
    { value: 'site-reliability-engineer', label: 'Site Reliability Engineer (SRE)' },
    { value: 'quality-assurance-engineer', label: 'Quality Assurance (QA) Engineer' },
    { value: 'data-scientist', label: 'Data Scientist' },
    { value: 'data-analyst', label: 'Data Analyst' },
    { value: 'data-engineer', label: 'Data Engineer' },
    { value: 'machine-learning-engineer', label: 'Machine Learning Engineer' },
    { value: 'ai-engineer', label: 'AI Engineer' },
    { value: 'ai-research-scientist', label: 'AI Research Scientist' },
    { value: 'product-manager', label: 'Product Manager' },
    { value: 'technical-product-manager', label: 'Technical Product Manager' },
    { value: 'product-owner', label: 'Product Owner' },
    { value: 'ux-ui-designer', label: 'UX/UI Designer' },
    { value: 'product-designer', label: 'Product Designer' },
    { value: 'systems-architect', label: 'Systems Architect' },
    { value: 'cloud-architect', label: 'Cloud Architect' },
    { value: 'solutions-architect', label: 'Solutions Architect' },
    { value: 'cybersecurity-analyst', label: 'Cybersecurity Analyst' },
    { value: 'penetration-tester', label: 'Penetration Tester (Ethical Hacker)' },
    { value: 'security-engineer', label: 'Security Engineer' },
    { value: 'database-administrator', label: 'Database Administrator (DBA)' },
    { value: 'network-engineer', label: 'Network Engineer' },
    { value: 'systems-administrator', label: 'Systems Administrator' },
    { value: 'it-support-specialist', label: 'IT Support Specialist' },
    { value: 'scrum-master', label: 'Scrum Master' },
    { value: 'agile-coach', label: 'Agile Coach' },
    { value: 'technical-writer', label: 'Technical Writer' },
    { value: 'game-developer', label: 'Game Developer' },
    { value: 'blockchain-developer', label: 'Blockchain Developer' },
    { value: 'embedded-systems-engineer', label: 'Embedded Systems Engineer' },
    // Business & Management
    { value: 'project-manager', label: 'Project Manager' },
    { value: 'program-manager', label: 'Program Manager' },
    { value: 'business-analyst', label: 'Business Analyst' },
    { value: 'management-consultant', label: 'Management Consultant' },
    { value: 'operations-manager', label: 'Operations Manager' },
    { value: 'supply-chain-manager', label: 'Supply Chain Manager' },
    { value: 'human-resources-manager', label: 'Human Resources (HR) Manager' },
    { value: 'recruiter', label: 'Recruiter' },
    { value: 'talent-acquisition-specialist', label: 'Talent Acquisition Specialist' },
    { value: 'accountant', label: 'Accountant' },
    { value: 'financial-analyst', label: 'Financial Analyst' },
    { value: 'investment-banker', label: 'Investment Banker' },
    { value: 'auditor', label: 'Auditor' },
    // Marketing & Sales
    { value: 'marketing-manager', label: 'Marketing Manager' },
    { value: 'digital-marketing-specialist', label: 'Digital Marketing Specialist' },
    { value: 'seo-specialist', label: 'SEO Specialist' },
    { value: 'content-strategist', label: 'Content Strategist' },
    { value: 'social-media-manager', label: 'Social Media Manager' },
    { value: 'brand-manager', label: 'Brand Manager' },
    { value: 'public-relations-specialist', label: 'Public Relations (PR) Specialist' },
    { value: 'sales-manager', label: 'Sales Manager' },
    { value: 'sales-representative', label: 'Sales Representative' },
    { value: 'account-executive', label: 'Account Executive' },
    { value: 'customer-success-manager', label: 'Customer Success Manager' },
    // Creative
    { value: 'graphic-designer', label: 'Graphic Designer' },
    { value: 'art-director', label: 'Art Director' },
    { value: 'copywriter', label: 'Copywriter' },
    { value: 'video-editor', label: 'Video Editor' },
    { value: 'photographer', label: 'Photographer' },
    { value: 'animator', label: 'Animator' },
    { value: 'industrial-designer', label: 'Industrial Designer' },
    { value: 'fashion-designer', label: 'Fashion Designer' },
    // Healthcare
    { value: 'registered-nurse', label: 'Registered Nurse (RN)' },
    { value:f: 'physician', label: 'Physician' },
    { value: 'pharmacist', label: 'Pharmacist' },
    { value: 'physical-therapist', label: 'Physical Therapist' },
    { value: 'medical-assistant', label: 'Medical Assistant' },
    { value: 'healthcare-administrator', label: 'Healthcare Administrator' },
    { value: 'biomedical-engineer', label: 'Biomedical Engineer' },
    // Education
    { value: 'teacher', label: 'Teacher' },
    { value: 'professor', label: 'Professor' },
    { value: 'instructional-designer', label: 'Instructional Designer' },
    { value: 'school-counselor', label: 'School Counselor' },
    { value: 'corporate-trainer', label: 'Corporate Trainer' },
    // Other
    { value: 'lawyer', label: 'Lawyer' },
    { value: 'paralegal', label: 'Paralegal' },
    { value: 'architect', label: 'Architect' },
    { value: 'civil-engineer', label: 'Civil Engineer' },
    { value: 'mechanical-engineer', label: 'Mechanical Engineer' },
    { value: 'electrical-engineer', label: 'Electrical Engineer' },
    { value: 'real-estate-agent', label: 'Real Estate Agent' },
    { value: 'chef', label: 'Chef' },
    { value: 'journalist', label: 'Journalist' },
    { value: 'research-scientist', label: 'Research Scientist' },
    { value: 'environmental-scientist', label: 'Environmental Scientist' },
    { value: 'pilot', label: 'Pilot' },
    { value: 'event-planner', label: 'Event Planner' },
    { value: 'librarian', label: 'Librarian' },
    { value: 'statistician', label: 'Statistician' },
    { value: 'actuary', label: 'Actuary' },
];
